import i18n from 'i18next'
import LanguageDetector from 'i18next-browser-languagedetector'
import { initReactI18next } from 'react-i18next'

void i18n
	.use(LanguageDetector)
	.use(initReactI18next)
	.init({
		debug: false,
		fallbackLng: 'en',
		interpolation: {
			escapeValue: false,
		},
		resources: {
			en: {
				translation: {
					common: { delete: 'Delete', cancel: 'Cancel', close: 'Close' },
					form: { select_placeholder: 'Please select', input_placeholder: 'Please input', upload_placeholder: 'Click to upload' },
					app: { list: 'App List', no_data_default: 'No App', no_title_default: 'No Title', no_description: 'No description', no_config_default_text: 'No Dify app config found.' },
					chat: { chat_list: 'Chat List', no_data_default: 'No Chat', new_chat: 'New Chat', rename: 'Rename', rename_success: 'Rename Success', delete: 'Delete', delete_confirm_title: 'Are you sure?', delete_confirm_content: 'Chat history cannot be restored.', delete_success: 'Delete Success', sidebar_close: 'Close Sidebar', sidebar_open: 'Open Sidebar', input_params_setting: 'Input Parameters Setting', input_disabled_between_chats: 'Params readonly after conversation starts.' },
					message: { response_time: 'Response Time', action_regenerate: 'Regenerate', action_copy: 'Copy', copy_success: 'Copy Success', annotation: 'Annotation', tts: 'Text-to-Speech', feedback_positive: 'Positive', feedback_negative: 'Negative', tool: { title_prefix: 'Used ', title_default: 'No Title' } },
					system: { theme: 'Theme', default_disclaimer_content: 'Content generated by AI, for reference only.' },
					debug: { title: 'Debug Mode', config_title: 'App Config', config_description: 'Enter app config in JSON.', use_sample: 'Use Sample', clear: 'Clear', save: 'Save', exit: 'Exit', exit_success: 'Config cleared', usage_title: 'Instructions', interface_schema_prefix: 'Config must comply with', interface_schema: 'Interface Schema', usage_item_2: 'Page will refresh after save.' },
				},
			},
			zh: {
				translation: {
					common: { delete: '删除', cancel: '取消', close: '关闭' },
					form: { select_placeholder: '请选择', input_placeholder: '请输入', upload_placeholder: '点击上传' },
					app: { list: '应用列表', no_data_default: '暂无应用', no_title_default: '暂无标题', no_description: '暂无描述', no_config_default_text: '暂无 Dify 应用配置' },
					chat: { chat_list: '对话列表', no_data_default: '暂无对话', new_chat: '新增对话', rename: '重命名', rename_success: '重命名成功', delete: '删除', delete_confirm_title: '确定删除吗？', delete_confirm_content: '删除后不可恢复。', delete_success: '删除成功', sidebar_close: '折叠侧边栏', sidebar_open: '展开侧边栏', input_params_setting: '对话参数设置', input_disabled_between_chats: '对话开始后参数不可修改' },
					message: { response_time: '回复时间', action_regenerate: '重新生成', action_copy: '复制', copy_success: '复制成功', annotation: '标注', tts: '语音朗读', feedback_positive: '点赞', feedback_negative: '点踩', tool: { title_prefix: '已使用', title_default: '暂无标题' } },
					system: { theme: '主题', default_disclaimer_content: '内容由 AI 生成, 仅供参考' },
				},
			},
		},
	})

export default i18n
