# 构建阶段
FROM node:22.21.1-alpine AS builder
WORKDIR /app

# 复制 Prisma schema
COPY packages/platform/prisma ./packages/platform/prisma/
COPY packages/platform/package.json ./packages/platform/
COPY packages/api/package.json ./packages/api/
COPY packages/components/package.json ./packages/components/
COPY packages/core/package.json ./packages/core/
COPY packages/helpers/package.json ./packages/helpers/
COPY packages/theme/package.json ./packages/theme/
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN npm install pnpm@10.8.1 -g
RUN pnpm install

# 复制所有源码
COPY packages/platform/ ./packages/platform/
COPY packages/api/ ./packages/api/
COPY packages/components/ ./packages/components/
COPY packages/core/ ./packages/core/
COPY packages/helpers/ ./packages/helpers/
COPY packages/theme/ ./packages/theme/
# components 子包中依赖了 react-app 的 tailwind.config.js，后续优化移除这个依赖关系
COPY packages/react-app/ ./packages/react-app/
COPY tsconfig.prod.json ./

# 构建子包
RUN pnpm build:pkgs
# 生成 Prisma 客户端
RUN pnpm --filter dify-chat-platform exec prisma generate
# 构建 platform
RUN pnpm --filter dify-chat-platform build


FROM node:22.21.1-alpine AS runner

WORKDIR /app

# 复制整个 standalone 目录（包含所有必需的文件和依赖）
COPY --from=builder /app/packages/platform/.next/standalone ./
COPY --from=builder /app/packages/platform/.next/static ./packages/platform/.next/static
COPY --from=builder /app/packages/platform/public ./packages/platform/public
# 复制 Prisma 生成的客户端文件（必需）
COPY --from=builder /app/packages/platform/prisma ./packages/platform/prisma
# Prisma 配置文件，执行 Prisma CLI 时必需
COPY --from=builder /app/packages/platform/prisma.config.ts ./packages/platform/prisma.config.ts
COPY packages/platform/docker/entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

ENV NODE_ENV=production
ENV PORT=5300

EXPOSE 5300

WORKDIR /app/packages/platform

# 入口脚本
ENTRYPOINT ["/docker-entrypoint.sh"]

# 启动
CMD ["node", "server.js"]
