import i18n from 'i18next'
import LanguageDetector from 'i18next-browser-languagedetector'
import { initReactI18next } from 'react-i18next'

await i18n
	// detect user language
	// learn more: https://github.com/i18next/i18next-browser-languageDetector
	.use(LanguageDetector)
	// pass the i18n instance to react-i18next.
	.use(initReactI18next)
	// init i18next
	// for all options read: https://www.i18next.com/overview/configuration-options
	.init({
		debug: true,
		fallbackLng: 'en',
		interpolation: {
			escapeValue: false, // not needed for react as it escapes by default
		},
		resources: {
			en: {
				translation: {
					common: {
						delete: 'Delete',
						cancel: 'Cancel',
						close: 'Close',
					},
					form: {
						select_placeholder: 'Please select',
						input_placeholder: 'Please input',
						upload_placeholder: 'Click to upload',
					},
					app: {
						list: 'App List',
						no_data_default: 'No App',
						no_title_default: 'No Title',
						no_description: 'No description',
						no_config_default_text: 'No Dify app config found, please contact the administrator.',
					},
					chat: {
						chat_list: 'Chat List',
						no_data_default: 'No Chat',
						new_chat: 'New Chat',
						rename: 'Rename',
						rename_success: 'Rename Success',
						delete: 'Delete',
						delete_confirm_title: 'Are you sure you want to delete this conversation?',
						delete_confirm_content: 'After deletion, the chat history cannot be restored.',
						delete_success: 'Delete Success',
						sidebar_close: 'Close Sidebar',
						sidebar_open: 'Open Sidebar',
						input_params_setting: 'Input Parameters Setting',
						input_disabled_between_chats:
							'Attention: Params will be reaonly if the conversation starts.',
					},
					message: {
						response_time: 'Response Time',
						action_regenerate: 'Regenerate Response',
						action_copy: 'Copy',
						copy_success: 'Copy Success',
						annotation: 'Annotation',
						tts: 'Text-to-Speech',
						feedback_positive: 'Positive Feedback',
						feedback_negative: 'Negative Feedback',
						tool: {
							title_prefix: 'Used ',
							title_default: 'No Title',
						},
					},
					system: {
						theme: 'Theme',
						default_disclaimer_content: 'Content generated by AI, for reference only.',
					},
					debug: {
						title: 'Debug Mode Configuration',
						config_title: 'App Config',
						config_description:
							'Please enter the application configuration array in JSON format. Each application must include info and requestConfig fields.',
						use_sample: 'Use Sample Config',
						clear: 'Clear Debug Config',
						save: 'Save Config',
						exit: 'Exit Debug Mode',
						exit_success: 'Debug config cleared',
						usage_title: 'Instructions',
						interface_schema_prefix: 'Config format must comply with',
						interface_schema: 'Interface Schema',
						usage_item_2:
							'The page will automatically refresh to apply new settings after saving configuration',
					},
				},
				debug: {
					title: 'Debug Mode Configuration',
					config_title: 'App Config',
					config_description:
						'Please enter the application configuration array in JSON format. Each application must include info and requestConfig fields.',
					use_sample: 'Use Sample Config',
					clear: 'Clear Debug Config',
					save: 'Save Config',
					exit: 'Exit Debug Mode',
					exit_success: 'Debug config cleared',
					usage_title: 'Instructions',
					interface_schema_prefix: 'Config format must comply with',
					interface_schema: 'Interface Schema',
					usage_item_2:
						'The page will automatically refresh to apply new settings after saving configuration',
				},
			},
			zh: {
				translation: {
					common: {
						delete: '删除',
						cancel: '取消',
						close: '关闭',
					},
					form: {
						select_placeholder: '请选择',
						input_placeholder: '请输入',
						upload_placeholder: '点击上传',
					},
					app: {
						list: '应用列表',
						no_data_default: '暂无应用',
						no_title_default: '暂无标题',
						no_description: '暂无描述',
						no_config_default_text: '暂无 Dify 应用配置，请联系管理员',
					},
					chat: {
						chat_list: '对话列表',
						no_data_default: '暂无对话',
						new_chat: '新增对话',
						rename: '重命名',
						rename_success: '重命名成功',
						delete: '删除',
						delete_confirm_title: '确定删除当前对话吗？',
						delete_confirm_content: '删除后，聊天记录将不可恢复。',
						delete_success: '删除成功',
						sidebar_close: '折叠侧边栏',
						sidebar_open: '展开侧边栏',
						input_params_setting: '对话参数设置',
						input_disabled_between_chats: '注意：对话开始后，参数设置将无法修改',
					},
					message: {
						response_time: '回复时间',
						action_regenerate: '重新生成回复',
						action_copy: '复制',
						copy_success: '复制成功',
						annotation: '标注',
						tts: '语音朗读',
						feedback_positive: '点赞',
						feedback_negative: '点踩',
						tool: {
							title_prefix: '已使用',
							title_default: '暂无标题',
						},
					},
					system: {
						theme: '主题',
						default_disclaimer_content: '内容由 AI 生成, 仅供参考',
					},
				},
			},
		},
	})

export default i18n
